name: Deployment Workflow

on: 
  push: 
    branches: [main]

jobs:
   test:
     uses: lisamariepleyer/WWE_Quiz_WebApp/.github/workflows/development.yml@main
     with:
      node-version: '18.x'
   
   build:
     name: Build Application
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
      
       - name: Setup node
         uses: actions/setup-node@v3
         with:
           node-version: '18.x'

       - name: Install dependencies
         uses: npm ci
         
       - name: Build project
         uses: npm run build
         
       - name: Upload build artifact
         uses: actions/upload-pages-artifact@v2
 
   deployment:
     name: Deploy Application
     runs-on: ubuntu-latest
     needs: [test, build]
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
      
       - name: Setup Github Pages
         uses: actions/configure-pages@v3
         
       - name: Download build artifact
         uses: actions/download-artifact@v3
      
       - name: Deploy to Github Pages
         uses: actions/deploy-pages@v2 
